name: Check run

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
  workflow_dispatch:

jobs:
  check-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - run: sudo apt-get update && sudo apt-get install -y nginx && sudo systemctl start nginx

    - name: ZAP Scan
      uses: ./
      id: action-api-scan
      with:
        target: 'https://github.com/Siddhant02082002/backend-testing2.0'
        allow_issue_writing: false
